### ISSUE TITLE
Repository 초기 작업환경 세팅 

### ISSUE THREAD

**Issue by Mule129** [Team-EverFlow/Koreasy#2]
## 필요한 기능
- Repository 초기 작업환경 세팅 

## 해야 할 일 
- [x] .gitignore 세팅
- [x] .prettierrc 세팅
- [x] .eslintrc 세팅
- [x] 프로젝트 초기 파일 초기화
- [x] 프로젝트 파일 구조 생성
- [x] redux, bootstrap 세팅

**Comment by SeoSangtae001027** [comment]
감사합니다
