### ISSUE TITLE
Today word View

### ISSUE THREAD

**Issue by Mule129** [Team-EverFlow/Koreasy#35]
## 필요한 기능
- TodayWordPage

## 해야 할 일 
- [x] 오늘의 단어 카드 작성
- [x] 오늘의 슬랭 카드 작성
- [ ] 예제 롱탭 카피 코드 작성
- [x] 단어 카드 뒤집기 구현
- [x] 단어 카드 모두 뒤집으면 출석 구현
- [x] 댓글 전송 및 초기화 구현

## 추가 컨텍스트
- 롱탭 카피 텍스트 코드는 구현에 시간이 많이 소요될 수도 있습니다

**Comment by HanGyeongjun** [comment]
롱탭에 2시간 이상의 개발시간 소요된다면 일단 해당 기능 배제하고 개발해주셔도 됩니다 @Mule129
